### ISSUE TITLE
Curl system binary non default location /usr/local/bin/curl instead of /usr/bin/curl

### ISSUE THREAD

**Issue by randomessence** [Homebrew/linuxbrew#345]
On the particular set-up I install to as a non root user, to my local directory, curl is not installed server wide to the location the linuxbrew ( and homebrew) looks for it.

~~~
[server ~] brew install sshfs
==> Installing dependencies for sshfs: autoconf, automake, libtool, gettext, osxfuse, libffi, glib
==> Installing sshfs dependency: autoconf
==> Downloading http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
Error: /usr/bin/curl is not executable
~~~

So if I do this to see where curl is in my PATH:

~~~
whereis curl
curl: /usr/local/bin/curl
~~~

This seems to be the relevant line:

https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/utils.rb#L166

So then if I do this command:

~~~
sed -ri  "s|  curl = Pathname.new '/usr/bin/curl'|  curl = Pathname.new '/usr/local/bin/curl'|g"  ~/.linuxbrew/Library/Homebrew/utils.rb
~~~

It fixes my problem and curl now works with the `brew install sshfs` command as intended.

What I am wondering is:

**1:** Is there a way I can change this without hard coding it or modifying the server setup? I cannot see a way to pass this env to brew when using `brew install ....` or another way to set this locally so that `brew` looks for curl in the place I want it to?

**2:** If the above is not possible maybe linuxbrew could could be a little more flexible in how it detects curl? Perhaps by checking the `whereis` result then setting that?

**Comment by sjackman** [comment]
Does changing `curl = Pathname.new '/usr/bin/curl'` to `curl = Pathname.new "curl"` resolve your issue?

**Comment by randomessence** [comment]
No unfortunatley, I did try that. If I do this below (and start a new SSH session)

~~~
  curl = Pathname.new "curl"
  puts ENV['PATH']
  raise "#{curl} is not executable" unless curl.exist? and curl.executable?
~~~

I get this:

~~~
[server ~] brew install wget
==> Installing wget dependency: libuuid
==> Downloading https://downloads.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz
/media/disk/home/username/bin:/media/disk/home/username/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/media/disk/home/username/.linuxbrew/Library/ENV/scm
Error: curl is not executable
~~~

So it is in my PATH for sure

~~~
[server ~] curl --version
curl 7.41.0 (x86_64-unknown-linux-gnu) libcurl/7.41.0 OpenSSL/1.0.1e zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
~~~

**Comment by sjackman** [comment]
Yes, definitely. That should probably be patched for Linuxbrew. Perhaps something like `HOMEBREW_PREFIX/bin:/usr/local/bin:/usr/bin:/bin`, or just use the user's PATH untouched.

**Comment by iggyvolz** [comment]
@sjackman Which would you prefer - the string one or the user's PATH?  I personally don't see any problem with passing the PATH in verbatim - there's really no standard place to leave executables which is why PATH exists in the first place.

**Comment by randomessence** [comment]
OK, so I tried this `$HOMEBREW_PREFIX/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin` and it did not make any difference. So i was wondering why it is basically ignoring all things PATH.

Then I noticed something when I was messing with stuff and I created a few errors, when I change [L166](https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/utils.rb#L166) to:

`curl = Pathname.new '/usr/bin/curl'` to `curl = Pathname.new "curl"`

The actual result is that the curl is being looked for in the root of the user directory.

So effectively `utils.rb` is doing this:  `~/curl` and it cannot find the executable hence the error is: `Error: /usr/bin/curl is not executable`

~~~
[server ~] whereis curl
curl: /usr/local/bin/curl /usr/include/curl
[sever ~] ln -s /usr/local/bin/curl ~/curl
~~~

So if I edit the [L166](https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/utils.rb#L166) to this: ` curl = Pathname.new "curl"` and then create a symlink in my non root user's home directory like this: `ln -s /usr/local/bin/curl ~/curl`

Now it works.

**Comment by sjackman** [comment]
@randomessence Using `which` should work:
```ruby
curl = which("curl") || Pathname.new("/usr/bin/curl")
raise "#{curl} is not executable" unless curl.exist? and curl.executable?
```

**Comment by sjackman** [comment]
@iggyvolz My preference for now is to use the string version. One design goal of Homebrew is not to depend on the state of the user's environment variables, and to build a consistent package between different machines. It's harder on Linux, because the systems are so heterogeneous, but I'd like to keep to that design goal.

**Comment by randomessence** [comment]
@sjackman your suggestion worked. Will you apply this fix to the main repo?

**Comment by sjackman** [comment]
Fixed. I went with this:
```ruby
  curl = which "curl" unless OS.mac?
  curl ||= Pathname.new '/usr/bin/curl'
```

**Comment by vikjam** [comment]
I have curl installed in an non-default location and I'm still getting this error. Could I get help troubleshooting this error?

**Comment by sjackman** [comment]
I believe it uses either `$HOMEBREW_PREFIX/opt/curl/bin/curl` or the `curl` found in your `PATH`. You could create a symlink from the `curl` that you want to use to `$HOMEBREW_PREFIX/opt/curl/bin/curl`

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/brew.sh#L114-L125

**Comment by vikjam** [comment]
Thanks for setting me in the right direction. I was able to get Homebrew curl working!
